split_val = 80
train_data = "evaluation/data_training.csv"
test_data = "evaluation/data_test.csv"
categories = ["M", "B"]
batch_size = 1
epochs = 500
learning_rate = 0.01
layers = (10, 5, 2)
seed = 1337
early_stoping = True
stopping_epochs = 35
