split_val = 80
train_data = "evaluation/data_training.csv"
test_data = "evaluation/data_test.csv"
categories = ["M", "B"]
batch_size = 1
epochs = 100
learning_rate = 0.01
dynamic_learning_rate = True
learning_rate_multiplier = 0.666
learning_rate_change_number = 6
layers = (5, 5, 2)
seed = 1337
